- name: Setup bits in AWX
  hosts: localhost
  gather_facts: no
  serial: 1
  tasks:
    - name: setup awx project
      include_role:
        name: awx-project
      when: setup_awx

    - name: setup awx template
      include_role:
        name: awx-qualys-template
      when: setup_awx 