- hosts: localhost
  tasks:
  - name: Execute Python Script using the script module
    ansible.builtin.script:
      cmd: qualys_asset_groups.py 
      executable: '/usr/bin/python'
    register: result

  - debug:
      msg: "{{ result }}"
